#!/bin/bash
TESTDIR=tests


cd "$( dirname "${BASH_SOURCE[0]}" )"

which coffeelint 2>&1 >/dev/null
COFFEELINT_AVAILABLE=$?
if [ "$COFFEELINT_AVAILABLE" -eq 0 ]; then
    echo "Running tests through coffeelint..."
    coffeelint -q $TESTDIR/*.coffee *.coffee | grep -e "^$" -v
fi

casperjs test $TESTDIR --pre=login.coffee --includes=inc.coffee
